### ISSUE TITLE
Action werkt niet meer

### ISSUE THREAD

**Issue by mrtn78** [Logius-standaarden/Automatisering#7]
de action voor het checken van de links werkt niet meer. Zie:

https://github.com/Logius-standaarden/Digikoppeling-Architectuur/actions/runs/3105720378/jobs/5077030722

ik weet dat ik 1 link heb toegevoegd naar een repo die nog op private staat en eerder gaven 3 andere links ook ee nfoutmelding maar nu gaat er iets in de scripting zelf mis.

**Comment by sanderke** [comment]
Breaking change in GitHub Actions: https://github.com/actions/runner-images/issues/6283
Ik ga opzoek naar een alternatief.
